### PR TITLE
Don't fail silently if app.json contains syntax errors

### LINKED ISSUE #6: Check if app.json and .env exists and throw errors for anything else
Currently, ff there's a syntax error in your `app.json` you won't get any feedback from `config-variables`.

### PR DESCRIPTION
**Pull request by simenbrekken**
Closes #6

### CODE REVIEW

File: src/helpers.js [hunk 1]
```diff
@@ -1,18 +1,19 @@
...
+const attemptPath = (filePath, callback) => (
+  fs.existsSync(filePath) ? callback(filePath) : undefined
+)
 
-export const readDotEnv = filePath => {
-  const config = attempt(() => dotenv.parse(fs.readFileSync(filePath)))
-  return isError(config) ? undefined : config
-}
+export const readAppjson = filePath => (
+  attemptPath(filePath, () => require(filePath)) // eslint-disable-line global-require
```
Comment (einarlove) [inline src/helpers.js]: Is `attemptPath` maybe an unneeded abstraction? Makes it more tricky to understand what gets returned from `readAppjson` if file doesn't exists.

`fs.existsSync(filePath) ? require(filePath) : undefined`
`fs.existsSync(filePath) ? dotenv.parse(fs.readFileSync(filePath)) : undefined`

**Comment by einarlove** [comment]
Want https://github.com/unfold/config-variables/pull/8 merged before this so we can test these changes.
